### PR TITLE
Playground Feature: Multiple contracts per account - Milestone 2

### PR DESCRIPTION
**Pull request by soetop**
## Description

This PR is for issue #21.

- [x] frontend: project default loading with multiple contracts per account 
- [x] frontend: contracts can be added, edited, deployed and deleted 
- [x] backend: support the above interactions

Check out the [demo video](https://youtu.be/Od1YxuHA0iA)

## To-dos and known-issues
- [x] export project folder
- [ ] remove comments starting with '//soe'
- [ ] fix Cadence code check for transactions as contract [declarations are not detected](https://user-images.githubusercontent.com/81572453/140640705-79b27723-0a13-444b-b7cb-5bb78b3ae1b0.png)
- [x] write test coverage
   - [initial coverage](https://github.com/onflow/flow-playground-api/pull/14/commits/974ff2a9f9d3bd1bba7525cdc3dfbe30af797104)
- [x] code [documentation](https://laser-teal-a79.notion.site/Notes-for-changes-Flipfest-21-b2c49263e87a4551b57826070fe566a6)
- [ ] write migration script

## Submission Links & Documents

_Backend_: flow-playground-api has been forked and work is done on [flip-21 branch](https://github.com/soetop/flow-playground-api/tree/flip-21)

Run datastore emulator first
```
  gcloud beta emulators datastore start
```

Then run the server
```
  make run-datastore
```

_Frontend_: flow-playground has been forked and work is done on [flip-21 branch](https://github.com/soetop/flow-playground/tree/flip-21)

```
  npm install
  npm run start
```

## Requirements Check

- Have have you met the milestone requirements? _yes_
- Have you included tests (if applicable)? _yes_ (comprehensive ones later)
- Have you met the contribution guidelines of the repos you have submitted code to (if applicable)? _yes_
- If this is the last milestone: _yes_
  - soetop: 100%

## Other Details

Check out the [demo video](https://youtu.be/Od1YxuHA0iA)

### CODE REVIEW

**Comment by MaxStalker** [comment]
@soetop can you raise PRs for proposed changes, so it would be easier to review?

**Comment by kerrywei** [comment]
> @soetop can you raise PRs for proposed changes, so it would be easier to review?

bump @soetop could you open PRs so that we can start review? right now the changes reside in a branch, making it very hard to add comments.

**Comment by soetop** [comment]
hello @maxstalker and @kerrywei,

you mean I merge to master then make PRs to respective repositories?

**Comment by kerrywei** [comment]
> hello @MaxStalker and @kerrywei,
> 
> you mean I merge to master then make PRs to respective repositories?

@soetop You can create a pull request via a forked repo by following https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by soetop** [comment]
thanks @kerrywei
I made PRs to respective repositories.
- https://github.com/onflow/flow-playground/pull/177
- https://github.com/onflow/flow-playground-api/pull/14

I am still working to fix a few know issues. One issue is regarding Cadence code check on transactions as can be seen [here](https://user-images.githubusercontent.com/81572453/140640705-79b27723-0a13-444b-b7cb-5bb78b3ae1b0.png) Deployed contracts are not found in declarations.

However, transactions can be executed successfully. I am looking into Cadence server code base to get clues. I would appreciate much if you could point me in the right direction.

**Comment by kerrywei** [comment]
Closing this PR given milestone 2 is not fully achieved -- the Max is working with @soetop in https://github.com/onflow/flow-playground/pull/177 and https://github.com/onflow/flow-playground-api/pull/14. 
Meanwhile, thank you for participating in the FLIP FEST @soetop and great job of finishing milestone 1!

**Comment by soetop** [comment]
I have made a few more commits. I would appreciate your reviews and will made necessary changes quickly.

For your reference, I have made documentation here:
https://laser-teal-a79.notion.site/Notes-for-changes-Flipfest-21-b2c49263e87a4551b57826070fe566a6

For quick reference, I have made a screen recording:
https://youtu.be/Wji5UD6HXZE

**Pull request closed without merging**
