### PR TITLE
Flow Swift SDK milestone-1, 2, 3, 4

### PR DESCRIPTION
**Pull request by lmcmz**
## Flow-Swift-SDK - Milestone 1, 2, 3, 4

This PR is for issue #20.

## SDK repo

https://github.com/zed-io/flow-swift

### Current Status

The flow-swift-SDK has completed all the essential part with test cases and example code. Some documentation has been added in the repo, we will add more documentation in the future. Moreover, we have created other swift SDK, which target for dapp and wallet app usage, [fcl-swift](https://github.com/zed-io/fcl-swift) and [flow-wallet-kit](https://github.com/zed-io/flow-wallet-kit) which are dependent on [flow-swift](https://github.com/zed-io/flow-swift). However, those two SDKs are still working in progress.

Blocks:

- [x] retrieve a block by ID
- [x] retrieve a block by height
- [x] retrieve the latest block

Collections:

- [x] retrieve a collection by ID

Events:

- [x] retrieve events by name in the block height range

Scripts:

- [x] submit a script and parse the response
- [x] submit a script with arguments and parse the response

Accounts:

- [x] retrieve an account by address
- [x] create a new account
- [x] deploy a new contract to the account
- [x] remove a contract from the account
- [x] update an existing contract on the account

Transactions:

- [x] retrieve a transaction by ID
- [x] sign a transaction (single payer, proposer, authorizer or combination of multiple)
- [x] submit a signed transaction
- [x] sign a transaction with arguments and submit it

### Milestones

- [x] Implement the gRPC layer of the SDK, allowing communication with the Flow blockchain
- [x] Accomplish transaction signing in a way that handles the complex algorithm / hashing / encoding for the user.
- [x] Meet and exceed Flow SDK guidelines
- [x] Complete documentation and common usage examples are available

Authors include:

    @ryankopinsky
    @bluesign
    @lmcmz

### CODE REVIEW

**Comment by sideninja** [comment]
> Hi @sideninja
> 
> Sorry for late reply. First of all, thanks for your feedback! Those are really great. 😻 Yeah, you are right. We need more documentation for the SDK. I will try out the jezz to auto-generate the doc, but yeah if you could send me some template that will be great.
> 
> As for the 3 questions you list above, let me give what I think:
> 
> https://github.com/zed-io/flow-swift/blob/main/Sources/Flow/Models/FlowTransaction.swift#L341
> 
> 1. Should this be moved from models to a network layer?
>    Since the gRPC code is auto generate, it already have the **Flow_Entities_Transaction.Signature**, I wanna have more controlling for my flow entity object so I create my own struct **Flow.TransactionSignature**. It need some converting between those two struct. 🤔I think keeping **Flow.TransactionSignature** in model is fine since it's close to business logic.
> 
> https://github.com/zed-io/flow-swift/blob/main/Sources/Flow/Models/FlowTransaction.swift#L199 2.Shouldn't this actually be checking for equality == instead of >=?
> 
> For those code, I was refer to fcl-js library. I guess it will be better to keep it consistent . here is the equivalent cod in fcl-js: https://github.com/onflow/fcl-js/blob/6818103ac65877873f0c62fcee119115783284f9/packages/fcl/src/transaction/index.js#L22-L27
> 
> 1. https://github.com/zed-io/flow-swift/blob/main/Sources/Flow/Models/FlowId.swift#L43
>    Yes, you are right. I will refactor this part. Nice catch！⚾️

Hi, no worries. I was reading through the SDK and I must say it's really well written so I didn't really find lots of things to improve. Great work.
I will provide a template by the end of the day and instructions how to fill it up.

**Comment by sideninja** [comment]
@lmcmz doing some more reading of the source code I think I've found a non-trivial issue. Transaction signing is done by using the [sign method](https://github.com/zed-io/flow-swift/blob/main/Sources/Flow/Models/FlowTransaction%2BSigner.swift#L18) which is a great approach I think we will also adopt in Go SDK as it hides the implementation complexity of signing payload vs signing envelope, BUT, user should be able to also do those two steps separately if they decide so. Imagine multiple party signatures where signing is done in multiple steps, although you can argue you can still just expose the sign method to support multiple invocation with different signers as arguments (and I even think that is a great argument) the fact is the current implementation of the sign method doesn't allow that if I'm not mistaken.

**Comment by sideninja** [comment]
Hi @lmcmz here is documentation template you should use for documenting your SDK https://github.com/onflow/sdks/tree/main/templates/documentation

**Comment by lmcmz** [comment]
Hi @sideninja , Good point, you are right. The current implementation doesn't have the ability to separate those two steps. I will make a fix for it. But yeah, this SDK is lacking in usage in other projects. It needs more feedbacks to make it more accessible and easy to use in real scenarios.

**Comment by kerrywei** [comment]
merge in the PR per Gregor's comment

**Pull request merged**
