### PR TITLE
Non-React FCL Usage: dapp example - Milestone 1

### PR DESCRIPTION
**Pull request by ic3guy**
# Non-React FCL Usage: dapp example - Milestone 1

## Description

This PR is for issue [#23](https://github.com/onflow/flip-fest/issues/23).

## Summary

I have implemented a front-end application built with Angular 12 that can interact and use the Flow Blockchain. 

- Solves the GRPC and other Node/Webpack issues
- Uses native Angular features: rxjs, observables and async pipes.
- Provides recipies for wrapping fcl calls to be consumed in Angular components
- Uses native Angular/rxjs testing, notably rxjs marble testing

## Submission Links & Documents

https://github.com/ic3guy/FlowAngularExample

Run with: `npm start`

### CODE REVIEW

**Comment by 10thfloor** [comment]
Thank you for your submission. Your app is working well. To qualify for the submission we'll need one more thing. 
- Please add a UI! If we're going to showcase your project, we want user's to have a good first impression!

**Comment by kerrywei** [comment]
> Thank you for your submission. Your app is working well. To qualify for the submission we'll need one more thing.
> 
> * Please add a UI! If we're going to showcase your project, we want to make a good first impression!
> 
> Thanks again for you submission.

@ic3guy please let us know in this PR when you have made improvements, and we are happy to give a second look!

**Comment by ic3guy** [comment]
Will do. I'll be adding some UI elements using Material.

**Review by 10thfloor — APPROVED** [review]

**Comment by kerrywei** [comment]
merge in the PR per Mac's approval

**Pull request merged**
