### PR TITLE
New Tool: Build a Flow SDK - milestone 2-3-4

### PR DESCRIPTION
**Pull request by nduplessis**
## Description

This PR is for issue #20.

This version of the Ruby SDK provides gRPC communication and a number of the SDK user stories, including script execution and single sig transaction signing and sending.

Usage documentation is available at https://github.com/glucode/flow_client

## Milestone 4

All user stories from the SDK guidelines have been completed and tests have been added that execute against the emulator.

Usages documentation can be found at https://github.com/glucode/flow_client

### Features

Blocks:
- [x] retrieve a block by ID
- [x] retrieve a block by height
- [x] retrieve the latest block

Collections:
- [x] retrieve a collection by ID 

Events:
- [x] retrieve events by name in the block height range

Scripts:
- [x] submit a script and parse the response
- [x] submit a script with arguments
- [x] create a script that returns complex structure and parse the response

Accounts:
- [x] retrieve an account by address
- [x] create a new account
- [x] deploy a new contract to the account
- [x] remove a contract from the account
- [x] update an existing contract on the account

Transactions: 
- [x] retrieve a transaction by ID
- [x] sign a transaction with same payer, proposer and authorizer
- [x] sign a transaction with different payer and proposer
- [x] sign a transaction with different authorizers using sign method multiple times
- [x] submit a signed transaction
- [x] sign a transaction with arguments and submit it

### CODE REVIEW

**Comment by kerrywei** [comment]
Thanks for the submission @nduplessis .
Before my teammate @sideninja  take a closer look, the fisr feedback is that we have a sdk documentation template https://github.com/onflow/sdks/blob/main/templates/documentation/template.md which aims to simplify & unify documentation and we encourage all SDKs to use it.

**Review by sideninja — COMMENTED** [review]
Good work on the implementation, however, I have some comments.

I think you should implement your own models for resources like blocks, collections, transactions etc so you can return an instance of such a model instead of returning raw access API responses. There are many benefits in doing so.
Examples:
https://github.com/glucode/flow_client/blob/b9713462681119c15d8a914dc3fd7252722b3078/lib/flow_client/client.rb#L239
https://github.com/glucode/flow_client/blob/b9713462681119c15d8a914dc3fd7252722b3078/lib/flow_client/client.rb#L262

Not doing so causes weird unpacking syntaxes like seen here: 
https://github.com/glucode/flow_client/blob/b9713462681119c15d8a914dc3fd7252722b3078/lib/flow_client/client.rb#L213

You could implement cadence models, so instead of passing raw cadence arguments, you could use native implemented cadence types.  
Examples:
https://github.com/glucode/flow_client/blob/b9713462681119c15d8a914dc3fd7252722b3078/spec/lib/flow_client/transaction_spec.rb#L277 

As mentioned please follow our documentation template and provide it in a file md/mdx in the repository.

Supporting contracts with account creation might be a good idea. Are there good reasons as to why you avoided that?
https://github.com/glucode/flow_client/blob/main/lib/flow_client/client.rb#L62

**Comment by nduplessis** [comment]
Thanks @sideninja

I've started on many of these items all ready and will merge them asap

**Comment by sideninja** [comment]
> Thanks @sideninja
> 
> I've started on many of these items all ready and will merge them asap

Great. You have by the end of this week to provide improvements based on the feedback. Let me know if you will have any questions.

**Comment by kerrywei** [comment]
@nduplessis Let us know when you have updates for review! 
Just a reminder: Nov 5th Friday might be the last day for our engineers to provide feedback (though you can for sure to continue iterate based on the feedback until Nov 7). Please take advantage of today and tomorrow to communicate with us more regarding project update. Looking forward to see your improvements!

**Comment by nduplessis** [comment]
Thanks for the heads up @kerrywei. Can you give me an idea which timezone the engineers are in as well by any chance?

**Comment by nduplessis** [comment]
@kerrywei @sideninja I've pushed my latest changes with the models as suggested. If you want to take a look you can do so on master branch. I'm working on the Cadence params and will add the ability to add contracts upon new account creation and will have that merge by Sunday

**Comment by sideninja** [comment]
> @kerrywei @sideninja I've pushed my latest changes with the models as suggested. If you want to take a look you can do so on master branch. I'm working on the Cadence params and will add the ability to add contracts upon new account creation and will have that merge by Sunday

Great, looking good. I will keep an eye on upcoming changes.

**Comment by sideninja** [comment]
I'm having a bit of hard time running some things due to M1 I guess, any suggestions there? Looks like grpc issue.
Error:
```
because it is not a compatible arch - /Library/Ruby/Gems/2.6.0/gems/grpc-1.41.1-universal-darwin/src/ruby/lib/grpc/2.6/grpc_c.bundle (LoadError)
```

**Comment by nduplessis** [comment]
Hey @sideninja, yeah that's probably M1 related. I'm looking into this for you and will revert soonest

**Comment by nduplessis** [comment]
@sideninja  this does indeed appear to be a pretty widespread issue: https://github.com/grpc/grpc/issues/24846#issuecomment-849076613

Sorry for not catching this, but unfortunately Apple Silicon is not available on most CI services yet. I'm quickly trying to see if I can rent an M1 in the cloud and will look for a solution

**Comment by sideninja** [comment]
> @sideninja this does indeed appear to be a pretty widespread issue: [grpc/grpc#24846 (comment)](https://github.com/grpc/grpc/issues/24846#issuecomment-849076613)
> 
> Sorry for not catching this, but unfortunately Apple Silicon is not available on most CI services yet. I'm quickly trying to see if I can rent an M1 in the cloud and will look for a solution

No worries, you can ping me when you want to test.

**Comment by nduplessis** [comment]
@sideninja OK so the grpc gem isn't in a great state for Apple Silicon at this point. I will need to do some more work to get the published gem to work correctly.

In the meantime you should be able to use it locally if you clone the repo, but you'll need to use Ruby 2.7.2 as a minimum.
This is pretty easy to install using rbenv

```bash
brew install rbenv ruby-build
rbenv install 2.7.2
rbenv local 2.7.2
```

Install the dependencies
```bash
bundle install
```

Run the unit tests
```bash
docker-compose up
bundle exec rspec
```

Use the gem in interactive ruby
```bash
irb -Ilib -rflow_client 
```

Let me know if this works for you please?

**Comment by kerrywei** [comment]
merge in the PR as milestones have been achieved

**Pull request merged**
