### PR TITLE
New Tool: Events indexing service - Milestone 3

### PR DESCRIPTION
**Pull request by chriswayoub**
This PR is for issue #15

## Submission Links & Documents

Remaining features for indexing service:

https://github.com/chriswayoub/flow-scanner

### CODE REVIEW

**Comment by tehranifar** [comment]
It seems to me that the deliverable here is a package vs. a service that was intended (like CLI or containerized image). Creating a service based on the package seems straightforward, is it something that has been done in the repo? The example repo seems like a service implementation of the package.

**Comment by chriswayoub** [comment]
You are correct, the example repo is the actual service implementation. Based on your feedback, I think renaming the repositories is probably the best option to make this more clear.

**Comment by tehranifar** [comment]
The goal would be to have one repo for both, prioritizing the service vs. the lib.

**Comment by chriswayoub** [comment]
This was also addressed on the PR for milestone 4, but just commenting here for clarity. The repositories have been restructured/renamed.

**Comment by tehranifar** [comment]
Thanks for the Milestone 3 submission. I have two points of feedback on this phase:
* When I run `flow-scanner` the logs provided are very minimal:
  ```
  → flow-scanner
  Broadcasting 11 events
  Broadcasting 2 events
  Broadcasting 6 events
  Broadcasting 13 events
  Broadcasting 8 events
  ```
  It's best to:
    * Print out all the configured environment variables on startup if possible.
    * Provide more information while running like:
      * Checking for new blocks ...
      * Processing block height X ...
      * New event observed with the actual event data
      * Broadcasting to X and Y ...
* The uniqueness check is done with `transactionId`:
  ```
  const lock = await uniqueChecker.acquireLock(transactionId)
  ```
  A single transaction can emit multiple events (and it's the norm because of fees) so you should deduplicate based on `transactiondId-eventIndex` which is guaranteed to be unique.

**Comment by chriswayoub** [comment]
I will add the additional logging at the "debug" log level.

As for uniqueness, the events are broadcast grouped by transaction (so the entire transaction is sent as a single message). In my opinion, you are going to have to assemble them back into a transaction for them to be useful for the consumer, so this made sense. If you are running multiple flow-scanner instances, then the idea would be to have a separate unique check table per instance (and if you are using SQS or SNS then you should configure a different MESSAGE_GROUP_ID per instance). I can add an additional configuration to make the lock_id unique per-instance (similar to the MESSAGE_GROUP_ID) if you think this is beneficial.

**Comment by tehranifar** [comment]
I'm thinking of the use case where we're listening to `event A` and `event B` with two different webhooks (this is common as webhooks are often single-purpose) and a single transaction ends up emitting both of them. Ideally, each webhook would be called with the corresponding event, but deduplicating based on transaction Id will drop one of them as duplicate. Am I understanding it correctly?

**Comment by chriswayoub** [comment]
For this setup, you'd be running two separate instances of the flow-scanner service (one listening for event A and emitting to consumer A, one listening for event B and emitting to consumer B).

Without any changes to the current service, you'd be able to set up two separate unique check files/tables and point each instance to one of them (using SQLITE_UNIQUE_CHECKER_FILE or DB_UNIQUE_CHECKER_TABLE).

If we want to be able to use one unique check file/table, then I can add a concept similar to the MESSAGE_GROUP_ID that you have with SNS and SQS and just make the lock_id something like `${transactionId}-${messageGroupId}` and you would use the same table/sqlite file, but specify a different messageGroupId value for each instance.

**Comment by tehranifar** [comment]
Makes sense. It might be worth making a section on docs about multiple event consumption and how the intended setup should look like.

**Comment by chriswayoub** [comment]
I do like the idea of adding a MESSAGE_GROUP_ID to the unique checker so it’s in parity with the SQS and SNS providers. I’ll get that done and update the docs, providing some example environment setups

**Comment by chriswayoub** [comment]
* A "group id" has been added to the sqlite and db unique checkers and readme has been updated. The new environment variable is `UNIQUE_CHECKER_GROUP_ID`
* I realized that you were probably seeing very little logging because the default log level is "error". I changed the default to "debug" so all logging messages will appear in the console by default

Make sure you update both repositories, and if you will need to `npm pack` the flow-scanner-lib repo and copy/npm install it in the flow-scanner repo to get everything working with the latest versions.

Let me know if there is anything else that should be done to wrap this milestone. Thanks!

**Comment by tehranifar** [comment]
Thank you for actioning the feedback points. I think this satisfies what I had in mind for this milestone. Great job!

**Review by tehranifar — APPROVED** [review]

**Pull request merged**
