### PR TITLE
CryptoDappy Feature: NFT marketplace #5 - Milestone 2 - Team Ancient Machine

### PR DESCRIPTION
**Pull request by NguyenIvan**
Special thanks to @bebner for all you help and support!

### CODE REVIEW

**Comment by bebner** [comment]
Hey @NguyenIvan , thanks for the milestone submission that certainly fulfils the requirements from the technical side. One question however: Could you draft up a short document outlining your creation process and giving an overview of the different moving pieces that can be submitted to the [Cryptodappy Learning Hub ](https://cryptodappy.com) as a mission? This way, everyone else can benefit from your experience.

**Comment by NguyenIvan** [comment]
Hi @bebner, of course I can. Please wait for me.

**Comment by NguyenIvan** [comment]
Hi @bebner,
I added [this file ](https://github.com/NguyenIvan/flip-fest/blob/main/submissions/issue-5/milestone-2/ancient-machine/report.md) to the submission. Please check it out.

**Comment by kerrywei** [comment]
merge in the PR per Ben's confirmation offline

**Pull request merged**
