### PR TITLE
Playground Feature: Improve the resource explorer 29 - Milestone 3

### PR DESCRIPTION
**Pull request by hichana**
## Description

This PR is for issue #29 - Playground Feature: Improve the resource explorer - Milestone 3.

I have added full support for a user-friendly integrated resources explorer functionality that maintains continuity of the user experience while allowing users to clearly explore account resources as they are updated by various transactions. While maintaining the aesthetic and user experience of the existing playground, as well as the codebase conventions and style, my solution allows users to achieve the following:

- quick way to inspect multiple accounts
- provide visual cues for items in storage
- message to the user which accounts have had their storage updated and which accounts processed the transaction to make that update
- autogenerate basic script or transaction templates by clicking on a stored item in the resources explorer

## Submission Links & Documents

- I made a comprehensive guide with notes and instructions on how to run the updated UI locally [HERE](https://github.com/hichana/flip-fest/blob/submissions/issue-%2329/milestone-3/hichana/submissions/issue-29/milestone-3/hichana/README.md).
- the PR for the milestone is [HERE](https://github.com/onflow/flow-playground/pull/175).

## Requirements Check

- Have have you met the milestone requirements? Yes
- Have you included tests (if applicable)? N/A
- Have you met the contribution guidelines of the repos you have submitted code to (if applicable)? Yes
- If this is the last milestone:
  - Demonstrate that you've met all the acceptance criteria (link to code, demos, instructions to run etc.).: Please see a comprehensive guide I made [HERE](https://github.com/hichana/flip-fest/blob/submissions/issue-%2329/milestone-3/hichana/submissions/issue-29/milestone-3/hichana/README.md).
  - Demonstrate that you've met all milestone requirements and highlight any extensions or additional work done.: Please see a comprehensive guide I made [HERE](https://github.com/hichana/flip-fest/blob/submissions/issue-%2329/milestone-3/hichana/submissions/issue-29/milestone-3/hichana/README.md).
  - Include a payout structure by percentage for each team member (ie. Bob: 20%, Alice: 80%).: @hichana: 100%

### CODE REVIEW

**Comment by kerrywei** [comment]
update: Max communicated with @hichana in Discord channel on this.

**Comment by hichana** [comment]
Hi @kerrywei \o/

Anything I can do for this one?

**Comment by kerrywei** [comment]
@hichana I believe my teammate and you discussed this PR in Discord? If that's not the case, cc @MaxStalker to clarify here

**Comment by MaxStalker** [comment]
🎉 **Milestone Achieved** 🎉

**Comment by kerrywei** [comment]
@hichana do you want to resolve the conflict so that we can merge in this PR?

**Comment by kerrywei** [comment]
if you can un-check in these .DS_Store files, the conflicts should be resolved

**Comment by hichana** [comment]
@MaxStalker @kerrywei I've removed the .DS_Store file, thank you.

**Review by kerrywei — APPROVED** [review]
merge in the PR per Max's comment

**Pull request merged**
