### PR TITLE
Flow-Rust-SDK - Milestone 4 Completed

### PR DESCRIPTION
**Pull request by MarshallBelles**
##  Flow-Rust-SDK - Milestone 4

This PR is for issue #20.

### Milestone 4 Completion:
- 4 [X] [Complete documentation and common usage examples are available](https://github.com/MarshallBelles/flow-rust-sdk/wiki)

Authors include:

    @marshallbelles - 90%
    @bluesign - 10%

### CODE REVIEW

**Comment by kerrywei** [comment]
(assigned a reviewer to help keep track of who is reviewing what)

**Review by sideninja — APPROVED** [review]

**Comment by MarshallBelles** [comment]
@sideninja just fixed the merge issue.

**Comment by MarshallBelles** [comment]
@sideninja do I need to worry about these getting merged before Monday?

**Comment by kerrywei** [comment]
> @sideninja do I need to worry about these getting merged before Monday? Or does that not matter as long as it's approved?

Hello @MarshallBelles , you do not need to worry about merging in this PR. As long as @sideninja does not have further suggestions, we'll soon merge in this PR for you

**Comment by fee1-dead** [comment]
Hello @MarshallBelles, I cloned your repository and found some problems, I opened https://github.com/MarshallBelles/flow-rust-sdk/issues/3. Hope the issues get fixed soon.

**Comment by MarshallBelles** [comment]
> Hello @MarshallBelles, I cloned your repository and found some problems, I opened [MarshallBelles/flow-rust-sdk#3](https://github.com/MarshallBelles/flow-rust-sdk/issues/3). Hope the issues get fixed soon.

Fixed.

**Pull request merged**
