### PR TITLE
Playground Feature: Multiple contracts per account - Milestone 1

### PR DESCRIPTION
**Pull request by soetop**
## Description

This PR is for issue #21.

- UI mockup and prototype is made.
- Suggestion on how multiple contracts will be stored per account

## Submission Links & Documents

- pull request has a [readme file](https://github.com/soetop/flip-fest/blob/main/submissions/issue-21/milestone-1/squidplay/flip-21-ms1-squidplay.md)
- mockup [image](https://user-images.githubusercontent.com/81572453/139025502-7b69fe75-8be4-4255-95c5-a8efa6f2f0de.png)
- prototype [video](https://youtu.be/Od1YxuHA0iA)

## Requirements Check

- Have have you met the milestone requirements? _yes_
- Have you included tests (if applicable)? _NA_
- Have you met the contribution guidelines of the repos you have submitted code to (if applicable)? _NA_
- If this is the last milestone: _no_

### CODE REVIEW

**Comment by kerrywei** [comment]
@soetop thank you for the submission! 
One suggestion for improvement on the UI: it would be nice if we can make the boundary of the tabs more clear. right now it's hard to spot the tab as they all look at the same "layer" (i.e. if you look at the tabs of Chrome or other browsers supporting multi-tab feature, you can easily identify the tabs). 
What do you think?

**Comment by MaxStalker** [comment]
Looks good, @soetop ! :)
I'd say we mark this one as 🎉 **Milestone Achieved** 🎉

**Comment by soetop** [comment]
@kerrywei, yes, I agree with your point. I will add in slight shade around border and subtle shadow to indicate that tabs are above the base layer.

**Comment by soetop** [comment]
updated in this commit: https://github.com/soetop/flow-playground/commit/4b52352d8895c2cbae39986c79d84a13e99d8033

Screen Shot 2021-11-07 at 5 20 26 PM

**Pull request merged**
